"use strict";

const {
  pgPool,
  POSTGRES_CONFIG,
  POSTGRES_ENABLED,
  POSTGRES_SSL,
  POSTGRES_SSL_MODE,
  POSTGRES_SSL_REJECT_UNAUTHORIZED,
  POSTGRES_URL,
  IS_PROD,
  IS_RENDER,
} = require("./postgresPool");

module.exports = {
  pgPool,
  POSTGRES_CONFIG,
  POSTGRES_ENABLED,
  POSTGRES_SSL,
  POSTGRES_SSL_MODE,
  POSTGRES_SSL_REJECT_UNAUTHORIZED,
  POSTGRES_URL,
  IS_PROD,
  IS_RENDER,
};
